[LEARN-5339] Implementar o endpoint GET /user
niina1/backend-test pull request #4
Opened 2022-06-08 13:23 UTC by ninaalves

[Implementar o endpoint GET/ user](https://trybe.atlassian.net/jira/software/c/projects/LEARN/boards/107?modal=detail&selectedIssue=LEARN-5339)

Os seguintes pontos serão avaliados:
Deve listar todos os Users e retorná-los na seguinte estrutura:

[
  {
    "id": "401465483996",
    "displayName": "Brett Wiltshire",
    "email": "brett@email.com",
    "image": "http://4.bp.blogspot.com/_YA50adQ-7vQ/S1gfR_6ufpI/AAAAAAAAAAk/1ErJGgRWZDg/S45/brett.png"
  }
]
A requisição deve ter token de autenticação nos headers e, caso contrário, retorne um código de status 401.

2022-06-10 12:28 UTC, katiacih requested changes

2022-06-10 12:28 UTC, katiacih commented on blog_api/lib/blog_api_web/views/users_view.ex
> +  alias BlogApiWeb.UsersView
Por que existe um alias pro próprio módulo? se voce quiser se referir ao modulo  BlogApiWeb.UsersView é possivel usar `__MODULE__`, o que acha de fazer essa troca?

2022-06-10 12:30 UTC, AdrielBento commented on blog_api/lib/blog_api.ex
> +  defdelegate list_users(), to: User.Get, as: :list_users
Pelo oque entendi, você está estruturando o projeto em uma pega mais de _use cases_ neh? Se for assim imagino que o`list_users` deveria ficar em outro arquivo -> `BlogApi.User.List`. Faz sentido?

2022-06-10 12:32 UTC, AdrielBento commented on blog_api/lib/blog_api_web/controllers/users_controller.ex
> +  require Logger
Esqueceu de remover?

2022-06-10 12:35 UTC, AdrielBento commented on blog_api/lib/blog_api_web/router.ex
> +    get("/user", UsersController, :get)
Acho que você consegue manter esse endpoint no mesmo scope, só teria que mexer na ordem
```elixir
scope "/api", BlogApiWeb do
    pipe_through(:api)

    post("/user", UsersController, :create)
    post("/login", UsersController, :login)
    
    pipe_through([:api, :auth])
    get("/user", UsersController, :get)
 end
```
_obs: Não tenho certeza se isso funciona, vai precisar testar_,

2022-06-21 13:50 UTC, niina1 commented on blog_api/lib/blog_api_web/router.ex
> +    get("/user", UsersController, :get)
funcionou colocando o  segundo pipe como pipe_through(:auth), do outro jeito falava que não podia definir o mesmo pipe duas vezes.

2022-06-22 13:51 UTC, merged